source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

gem 'json'
gem 'haml'
gem 'haml-rails'
gem 'dynamic_form'
gem 'sass'

gem 'roo'
gem 'spreadsheet'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'jquery-ui-sass-rails'
  
  # gem 'blockuijs-rails',  :git => 'git://github.com/rusanu/blockuijs-rails.git'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'fullcalendar-rails'

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-qtip2-rails'

gem 'jquery-ui-themes'

gem 'bootstrap-wysihtml5-rails'

gem "rubyzip",  "~> 1.3.0"

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# gem "eventmachine"
# gem 'thin'

# Use unicorn as the app server
#gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
